# Generated by Django 2.2.19 on 2021-03-26 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_nascimento', models.DateField(help_text='Formato DD/MM/AAAA', verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('matricula', models.IntegerField(unique=True, verbose_name='Matrícula')),
                ('cnh', models.CharField(choices=[('Não possui', 'Não possui'), ('Categoria A', 'Categoria A'), ('Categoria B', 'Categoria B'), ('Categoria C', 'Categoria C'), ('Categoria D', 'Categoria D'), ('Categoria E', 'Categoria E'), ('ACC', 'ACC')], max_length=20, verbose_name='CNH')),
                ('situacao', models.CharField(choices=[('1ª Habilitação', '1ª Habilitação'), ('Renovação', 'Renovação'), ('CRCI', 'CRCI')], max_length=20, verbose_name='Situação da Carteira')),
                ('categoria', models.CharField(choices=[('Categoria A', 'Categoria A'), ('Categoria B', 'Categoria B'), ('Categoria C', 'Categoria C'), ('Categoria D', 'Categoria D'), ('Categoria E', 'Categoria E'), ('ACC', 'ACC')], max_length=20, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária')),
            ],
            options={
                'verbose_name': 'Conteúdo',
                'verbose_name_plural': 'Conteúdos',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_nascimento', models.DateField(help_text='Formato DD/MM/AAAA', verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('matricula', models.IntegerField(unique=True, verbose_name='Matrícula')),
                ('cnh', models.CharField(choices=[('Não possui', 'Não possui'), ('Categoria A', 'Categoria A'), ('Categoria B', 'Categoria B'), ('Categoria C', 'Categoria C'), ('Categoria D', 'Categoria D'), ('Categoria E', 'Categoria E'), ('ACC', 'ACC')], max_length=20, verbose_name='CNH')),
                ('especializacao', models.CharField(choices=[('Instrutor Prático', 'Instrutor Prático'), ('Instrutor Teórico', 'Instrutor Teórico')], max_length=20, verbose_name='Especialização')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('max_aluno', models.IntegerField(verbose_name='Quantidade de alunos por turma')),
                ('alunos', models.ManyToManyField(to='aplic.Aluno')),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Conteudo')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.Professor')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
    ]
