# Generated by Django 2.2.19 on 2021-06-09 19:08

import aplic.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_nascimento', models.DateField(help_text='Formato DD/MM/AAAA', verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('matricula', models.IntegerField(unique=True, verbose_name='Matrícula')),
                ('cnh', models.CharField(choices=[('Não possui', 'Não possui'), ('Categoria A', 'Categoria A'), ('Categoria B', 'Categoria B'), ('Categoria C', 'Categoria C'), ('Categoria D', 'Categoria D'), ('Categoria E', 'Categoria E'), ('ACC', 'ACC')], max_length=20, verbose_name='CNH')),
                ('esta_ativo', models.BooleanField(default=True, verbose_name='Aluno em Atividade')),
                ('situacao', models.CharField(choices=[('1ª Habilitação', '1ª Habilitação'), ('Renovação', 'Renovação'), ('CRCI', 'CRCI')], max_length=20, verbose_name='Situação da Carteira')),
                ('categoria', models.CharField(choices=[('Categoria A', 'Categoria A'), ('Categoria B', 'Categoria B'), ('Categoria C', 'Categoria C'), ('Categoria D', 'Categoria D'), ('Categoria E', 'Categoria E'), ('ACC', 'ACC')], max_length=20, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária')),
            ],
            options={
                'verbose_name': 'Conteúdo',
                'verbose_name_plural': 'Conteúdos',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complemento', models.CharField(max_length=255, verbose_name='Complemento')),
                ('numero', models.CharField(max_length=9, verbose_name='Número')),
                ('logradouro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Cidade')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, unique=True, verbose_name='UF')),
                ('nome', models.CharField(max_length=55, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_nascimento', models.DateField(help_text='Formato DD/MM/AAAA', verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('matricula', models.IntegerField(unique=True, verbose_name='Matrícula')),
                ('cnh', models.CharField(choices=[('Não possui', 'Não possui'), ('Categoria A', 'Categoria A'), ('Categoria B', 'Categoria B'), ('Categoria C', 'Categoria C'), ('Categoria D', 'Categoria D'), ('Categoria E', 'Categoria E'), ('ACC', 'ACC')], max_length=20, verbose_name='CNH')),
                ('esta_ativo', models.BooleanField(default=True, verbose_name='Professor em Atividade')),
                ('especializacao', models.CharField(choices=[('Instrutor Prático', 'Instrutor Prático'), ('Instrutor Teórico', 'Instrutor Teórico')], max_length=20, verbose_name='Especialização')),
                ('facebook', models.CharField(blank=True, max_length=200, verbose_name='Facebook')),
                ('linkedin', models.CharField(blank=True, max_length=200, verbose_name='Linkedin')),
                ('twitter', models.CharField(blank=True, max_length=200, verbose_name='Twitter')),
                ('instagram', models.CharField(blank=True, max_length=200, verbose_name='Instagram')),
                ('foto', stdimage.models.StdImageField(blank=True, null=True, upload_to=aplic.models.get_file_path, verbose_name='Foto')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Endereco')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('esta_apto', models.BooleanField(default=True, verbose_name='Apto para Uso')),
                ('categoria', models.CharField(choices=[('Categoria A', 'Categoria A'), ('Categoria B', 'Categoria B'), ('Categoria C', 'Categoria C'), ('Categoria D', 'Categoria D'), ('Categoria E', 'Categoria E'), ('ACC', 'ACC')], max_length=20, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('max_aluno', models.IntegerField(verbose_name='Quantidade de alunos max de alunos')),
                ('alunos', models.ManyToManyField(to='aplic.Aluno')),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Conteudo')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.Professor')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Cidade')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Cidade')),
            ],
            options={
                'verbose_name': 'Logradouro',
                'verbose_name_plural': 'Logradouros',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Estado'),
        ),
        migrations.CreateModel(
            name='AulaTeorica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Formato DD/MM/AAAA', verbose_name='Data')),
                ('duracao', models.IntegerField(help_text='Quantidade de Horas', verbose_name='Duração')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Turma')),
            ],
            options={
                'verbose_name': 'Aula Teórica',
                'verbose_name_plural': 'Aulas Teóricas',
            },
        ),
        migrations.CreateModel(
            name='AulaPratica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Formato DD/MM/AAAA', verbose_name='Data')),
                ('duracao', models.IntegerField(help_text='Quantidade de Horas', verbose_name='Duração')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Professor')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Veiculo')),
            ],
            options={
                'verbose_name': 'Aula Prática',
                'verbose_name_plural': 'Aulas Práticas',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Endereco'),
        ),
    ]
