# Generated by Django 2.2.19 on 2021-03-26 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('esta_apto', models.BooleanField(default=True, verbose_name='Apto para Uso')),
                ('categoria', models.CharField(choices=[('Categoria A', 'Categoria A'), ('Categoria B', 'Categoria B'), ('Categoria C', 'Categoria C'), ('Categoria D', 'Categoria D'), ('Categoria E', 'Categoria E'), ('ACC', 'ACC')], max_length=20, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='esta_ativo',
            field=models.BooleanField(default=True, verbose_name='Aluno em Atividade'),
        ),
        migrations.AddField(
            model_name='professor',
            name='esta_ativo',
            field=models.BooleanField(default=True, verbose_name='Professor em Atividade'),
        ),
        migrations.CreateModel(
            name='AulaTeorica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Formato DD/MM/AAAA', verbose_name='Data')),
                ('duracao', models.IntegerField(help_text='Quantidade de Horas', verbose_name='Duração')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Turma')),
            ],
            options={
                'verbose_name': 'Aula Teórica',
                'verbose_name_plural': 'Aulas Teóricas',
            },
        ),
        migrations.CreateModel(
            name='AulaPratica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Formato DD/MM/AAAA', verbose_name='Data')),
                ('duracao', models.IntegerField(help_text='Quantidade de Horas', verbose_name='Duração')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Professor')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Veiculo')),
            ],
            options={
                'verbose_name': 'Aula Prática',
                'verbose_name_plural': 'Aulas Práticas',
            },
        ),
    ]
