# Generated by Django 2.2.19 on 2021-06-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='logradouro',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Rua'),
        ),
    ]
