# Generated by Django 2.2.19 on 2021-06-09 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_auto_20210609_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Logradouro'),
        ),
    ]
