# Generated by Django 2.2.19 on 2021-06-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_auto_20210609_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='logradouro',
            name='cep',
            field=models.CharField(default='', max_length=8, verbose_name='CEP'),
            preserve_default=False,
        ),
    ]
