# Generated by Django 2.2.19 on 2021-06-07 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_auto_20210607_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logradouro',
            options={'ordering': ['id'], 'verbose_name': 'Logradouro', 'verbose_name_plural': 'Logradouros'},
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Cidade'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Cidade'),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complemento', models.CharField(max_length=255, verbose_name='Complemento')),
                ('numero', models.CharField(max_length=9, verbose_name='Número')),
                ('logradouro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Cidade')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['id'],
            },
        ),
    ]
